version: '3'
networks:
  ekg_net:
    driver: bridge
services:
  ekg:
    build: .
    image: bloombyte/ekg:latest
    volumes:
      - /home/dev/ekg/.env:/django/.env
    ports:
      - "9700:8000"
    depends_on:
      - qcluster
    entrypoint: ./entrypoint.sh
    networks:
      - ekg_net

  qcluster:
    build: .
    image: bloombyte/ekg:latest
    volumes:
      - /home/dev/ekg/.env:/django/.env
    command: python manage.py qcluster
    restart: always
    networks:
      - ekg_net
