# Generated by Django 5.0.7 on 2024-07-19 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ticker", models.CharField(max_length=120, unique=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
                "ordering": ["-added_at"],
            },
        ),
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "market",
                    models.CharField(
                        choices=[
                            ("reg", "Regular"),
                            ("FUT", "Future"),
                            ("ODL", "Odd Lot"),
                        ],
                        max_length=20,
                    ),
                ),
                ("previous_close", models.FloatField()),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
                ("change", models.FloatField()),
                ("volume", models.FloatField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rate",
                "verbose_name_plural": "Rates",
                "ordering": ["-added_at"],
            },
        ),
    ]
