# Generated by Django 5.0.7 on 2024-07-19 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="market",
            field=models.CharField(
                choices=[("REG", "Regular"), ("FUT", "Future"), ("ODL", "Odd Lot")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rate",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates",
                to="stocks.stock",
            ),
        ),
    ]
