# Generated by Django 5.0.7 on 2024-07-19 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0002_alter_rate_market_alter_rate_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="rate",
            name="trend",
            field=models.CharField(
                choices=[("up", "Up"), ("down", "Down"), ("neutral", "Neutral")],
                default="neutral",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="rate",
            name="stock",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rate",
                to="stocks.stock",
            ),
        ),
    ]
